---
title: "PA1_template.Rmd"
author: "KS"
date: "1/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Loading and preprocessing the data

researchdata <- read.csv("C:/Users/kavis/Documents/Kavi files/Git-R Files/datasciencecoursera/ReproducibleRs/activity.csv")
        
library(ggplot2)

researchdata$date <- as.POSIXct(researchdata$date, "%Y-%m-%d")
weekday <- weekdays(as.Date(researchdata$date))
researchdata <- cbind(researchdata,weekday)
clean <- researchdata[!is.na(researchdata$steps),]
summary(researchdata)
head(researchdata)

##What is mean total number of steps taken per day?
totalSteps <- with(researchdata, aggregate(steps, 
                                           by = list(date), 
                                           FUN = sum,
                                           na.rm = TRUE))
names(totalSteps) <- c("date", "steps")

##Make a histogram of the total number of steps taken each day
hist(totalSteps$steps, main = "Total number of steps taken per day", 
                       xlab = "Total steps taken per day", 
                       col = "red", 
                       ylim = c(0,20), 
                       breaks = 5)
                       
##Calculate and report the mean and median of the total number of steps taken per day
as.integer(mean(totalSteps$steps))
as.integer(median(totalSteps$steps))

##What is the average daily activity pattern?
avgpattern <- aggregate(researchdata$steps, 
                        by=list(researchdata$interval), 
                        FUN=mean, 
                        na.rm=TRUE)
names(avgpattern) <- c("interval", "mean")
plot(avgpattern$interval, avgpattern$mean, 
                          type = "l", 
                          col="red", 
                          lwd = 2, 
                          xlab="Interval", 
                          ylab="Average number of steps", 
                          main="Average number of steps per intervals")
                                  
##Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
avgpattern[which.max(avgpattern$mean), ]$interval

##Imputing missing values
sum(is.na(researchdata$steps))

##Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
imputedSteps <- avgpattern$mean[match(researchdata$interval,avgpattern$interval)]

##Create a new dataset that is equal to the original dataset but with the missing data filled in.
newdataset <- transform(researchdata, 
                        steps = ifelse(is.na(researchdata$steps), 
                        yes = imputedSteps, 
                        no = researchdata$steps))
total_newsteps <- aggregate(steps ~ date, newdataset, sum)
names(total_newsteps) <- c("date", "daily_steps")

##Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?
hist(total_newsteps$daily_steps, col = "red", 
                                 xlab = "Total steps per day", 
                                 ylim = c(0,30), 
                                 main = "Total number of steps taken each day",                                   breaks = seq(0,25000,by=2500))
                                 
mean(total_newsteps$daily_steps)
median(total_newsteps$daily_steps)

##Are there differences in activity patterns between weekdays and weekends?

        
newdataset$RealDate <- as.Date(newdataset$date, format = "%Y-%m-%d")
newdataset$weekday <- weekdays(newdataset$RealDate)
newdataset$DayType <- ifelse(newdataset$weekday=='Saturday' | newdataset$weekday=='Sunday', 'weekend','weekday')
head(newdataset,n=10)

activity_by_date <- aggregate(steps~interval+DayType,data=newdataset,
                              FUN=mean,na.action=na.omit)
activity_by_date$time <- avgpattern$interval/100
j <- ggplot(activity_by_date, aes(time, steps))
j+geom_line(col="red")+ggtitle("Average steps per time interval: weekdays vs. weekends")+xlab("Time")+ylab("Steps")+theme(plot.title = element_text(face="bold", size=12))+facet_grid(DayType ~ .)


